#!/bin/bash
RPMBUILD_DIR=~/rpmbuild
RPM_SOURCES_DIR=$RPMBUILD_DIR/SOURCES
DIR_SOURCE=../../../hunspell-hr

PACKAGE_NAME=hunspell-hr
PACKAGE_VER=2.1
PACKAGE_REL=20190201
FILE_PACKAGE_SPEC=$PACKAGE_NAME.spec
FILE_PACKAGE_SOURCE=$RPM_SOURCES_DIR/$PACKAGE_NAME-$PACKAGE_VER-$PACKAGE_REL.tar.gz

tar czf $FILE_PACKAGE_SOURCE $DIR_SOURCE/hr_HR.aff $DIR_SOURCE/hr_HR.dic $DIR_SOURCE/README_hr_HR.txt
rpmbuild -ba $FILE_PACKAGE_SPEC
